// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llsjefacqvmagueepqwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsc2plZmFjcXZtYWd1ZWVwcXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjUxMjksImV4cCI6MjA2OTM0MTEyOX0.8kXfw__-YhBV6pW5D80eS1XNMfwiD9r4Ww5cRAbH7ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});